### ISSUE TITLE
trouble using nipype's csv writer with dataframes

### ISSUE THREAD

**Issue by binarybottle** [binarybottle/mhealthx#11]
How do I add a single-row pandas DataFrame to a csv file using nipype?

The function below fails in two ways:
1. can't exec an equal statement, and don't want to!
2. dataframe column names are arbitrary strings.

def row_to_table(row_data, output_table):
    """
    Add row to table using nipype (thread-safe in multi-processor execution).

    (Requires Python module lockfile)

    Parameters
    ----------
    row_data : pandas DataFrame
        row of data
    output_table : string
        add row to this table file

    Examples
    --------
    >>> import pandas as pd
    >>> from mhealthx.data_io import row_to_table
    >>> row_data = pd.DataFrame({'test1.A 0': ['A0'], 'test1.B 0': [3.14159], 'test1.C 0': ['']})
    >>> output_table = 'test.csv'
    >>> row_to_table(row_data, output_table)
    """
    from nipype.algorithms import misc

    addrow = misc.AddCSVRow()
    addrow.inputs.in_file = output_table
    columns = row_data.columns
    values = row_data.values
    for icol, col in enumerate(columns):
        eval("addrow.inputs.{0} = '{1}'".format(col, values[0][icol]))
    addrow.run()

**Comment by satra** [comment]
```
addrow = misc.AddCSVRow()
addrow.inputs.in_file = output_table
addrow.inputs.set(**row_data.to_dict())
res = addrow.run()
```

**Comment by binarybottle** [comment]
Great!  I see it saves a dict in each cell of the table -- how do I save just the contents of the dicts as entries to the csv table?

**Comment by satra** [comment]
the reason you are seeing dicts is because `row_data` is still a `DataFrame`. for addrow to work properly, row_data has to be a pandas Series, so you have to explicitly extract the row. for example,

row_data = dataframeobj.ix[0, :]

or some such.

**Comment by binarybottle** [comment]
Works beautifully -- thank you!

I wish the original column order were maintained, but understand that this isn't possible with dictionaries.
