### ISSUE TITLE
Disappearing files!

### ISSUE THREAD

**Issue by binarybottle** [binarybottle/mhealthx#12]
While running "mhealthx --phonation syn4590865 -t /software --stop 5 --reports" I see audio files appear and then disappear in the working directory.  Because they disappear, when I run the same command again, all files need to be downloaded again.

**Comment by satra** [comment]
running the command again, should only depend on input state, not local state. we discussed why nipype deletes unnecessary files, but that shouldn't be the reason for a node to rerun.

**Comment by binarybottle** [comment]
This is with an updated, one-node, glorified workflow (no preemptive file strings or chicanery).  Why would they disappear now?

**Comment by satra** [comment]
it's not one of the outputs of the node. any local temporary files that are not outputs of the node are removed after execution. change the config if you would like to keep them. however, the node should not rerun because of the removal of files. the node only reruns if the inputs have changed.

**Comment by binarybottle** [comment]
I see!  Perhaps the culprit is the input "feature_table" -- because I am adding to this table, it is changing.  I could hardcode this into the openSMILE function...

**Comment by binarybottle** [comment]
That was it -- fixed!
