### ISSUE TITLE
How to tolerate failed processes?

### ISSUE THREAD

**Issue by binarybottle** [binarybottle/mhealthx#5]
When I run mhealthx on 1,000 audio files, nipype stopped when ffmpeg tried to convert an incomplete file, generating the error below.  How do I make sure that nipype still processes all of the other audio files, and continues on to construct a feature table at the end of the pipeline (with empty cells for failed files)?

----
Exception: Subnodes of node: convert_phonation_file failed:
Subnode 954 failed
Error:
Command:
ffmpeg -i /Users/arno/mhealthx_cache/mhealthx/retrieve_phonation_file/mapflow/_retrieve_phonation_file954/audio_audio.m4a-2d4631c3-1f7d-4a42-bc5b-4ddb737a9b3b7521126929657780583.tmp.m4a -ac 2 /Users/arno/mhealthx_cache/mhealthx/retrieve_phonation_file/mapflow/_retrieve_phonation_file954/audio_audio.m4a-2d4631c3-1f7d-4a42-bc5b-4ddb737a9b3b7521126929657780583.tmp.m4a.wav
Standard output:
Standard error:
ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: 
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbb5182c800] moov atom not found
/Users/arno/mhealthx_cache/mhealthx/retrieve_phonation_file/mapflow/_retrieve_phonation_file954/audio_audio.m4a-2d4631c3-1f7d-4a42-bc5b-4ddb737a9b3b7521126929657780583.tmp.m4a: Invalid data found when processing input
Return code: 1
Interface CommandLine failed to run. 
Interface Function failed to run. 
150904-05:33:51,561 workflow INFO:
	 ***********************************
150904-05:33:51,561 workflow ERROR:
	 could not run node: mhealthx.convert_phonation_file
150904-05:33:51,561 workflow INFO:
	 crashfile: /Users/arno/Software/mhealthx/crash-20150904-053350-arno-convert_phonation_file.pklz
150904-05:33:51,561 workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/software/mhealthx/mhealthx/mhealthx", line 466, in <module>
    Flow.run(plugin=args.plugin)
  File "/software/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 700, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/software/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 56, in run
    report_nodes_not_run(notrun)
  File "/software/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/base.py", line 92, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by satra** [comment]
nipype as it stands will not continue with files nodes that crash. mapnode could potentially be augmented to allow the output list to include those that didn't run, but that would need additional semantics and checks for inputs down the line.

iterables on the other hand will crash a specific branch of the graph when a process fails. so if you turn every file into an indexed iterable (you don't want filepaths being used inside node directory paths)

in this particular case it seems this is a fundamental step to future processing. why don't you eliminate any inputs that cannot be processed?

**Comment by binarybottle** [comment]
Do you know how to check whether an audio .wav file is a valid file?  Perhaps I could do a try: on the ffmpeg audio converter command, and except: would return None, and I would just carry None through all of the subsequent functions?

**Comment by satra** [comment]
from the error above it looks like the converter is failing. are you trying to do anything across these files? if not it does seem that you want a workflow per file, which would make using iterables the most appropriate thing and letting those branches that fail crash.

**Comment by binarybottle** [comment]
Yes, ffmpeg can't read/convert the file.  I don't want nodes simply crashing, because at the end of the pipeline, all branches merge to write features extracted from the audio files to a feature table (node->mapnode->mapnode---->node.

**Comment by satra** [comment]
i'm sure i'm not understanding what you are trying to do. nipype also has a csv writer, that can insert rows into a table.

do you need information across files in any processing stage in your workflow? or are they running in parallel?

**Comment by binarybottle** [comment]
I didn't know about nipype's csv writer!

The first node, retrieve_phonation_rows, creates a list of dataframes that correspond to the rows of a Synapse table.  Each row has a corresponding audio file.  The following mapnodes (retrieve_phonation_file, rename_phonation_file, convert_phonation_file, rename_converted_phonation_file, openSMILE, format_openSMILE_output) process these audio files in parallel, then converge on nodes combine_openSMILE_outputs and merge_metadata_and_openSMILE, which terminate at node construct_openSMILE_feature_table.
 
![graph dot](https://cloud.githubusercontent.com/assets/236532/9686623/b25a9c98-52d9-11e5-851e-833bfba613d7.png)

**Comment by satra** [comment]
it does seem that you don't have any cross-file operation. i would not do this with mapnodes, to many failure options. this seems like a simple workflow per file.

**Comment by binarybottle** [comment]
True -- no cross-file operation for first-order feature extraction, but perhaps later there will be for aggregate or higher-order or multimodal features.  Are you suggesting that the first node reside outside the workflow, and to run each file through the workflow independently as a separate command submitted to a cluster.  Then grab the audio files with DataGrabber, as we do to parallelize the processing of subjects in brain imaging workflows like mindboggle?  Would I then have to write a followup script to merge the corresponding parts of the table that are processed separately?

**Comment by binarybottle** [comment]
Currently going ahead with MapNode chain, carrying along 'None' values to indicate which rows did not process and should be left blank in the final feature table.  try: except: surrounding each function will reduce the probability of errors halting the workflow.  Testing now on 1,000 rows...
